server:
  port: ${product-service.port:8030}

spring:
  application:
    name: product-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:7001
        username: nacos
        password: nacos